
title: Anatolian Market
description: Curated Middle Eastern & Anatolian picks with clean, fast UX.
baseurl: ""
url: ""
markdown: kramdown
theme: null

amazon_disclaimer: "As an Amazon Associate I earn from qualifying purchases."

nav:
  - title: Home
    url: /
  - title: Coffee & Tea
    url: /categories/coffee-tea/
  - title: Kitchen
    url: /categories/kitchen/
  - title: Wellness
    url: /categories/wellness/
  - title: Deals
    url: /deals/
  - title: About
    url: /about/

defaults:
  - scope:
      path: ""
    values:
      layout: default

# GitHub Pages safe settings: no custom plugins
exclude:
  - README.md
  - LICENSE
